--[[

Hello thank you for using my animation!
if you want to use my animation for your game, you can use it for free!
if you dont know how to use:
 1. Go to Animation selection in Avatar tab
 2. Click on the Rig and and publish the animation (you cant use it if you dont)
 3. Go to the script that was crouch script and put the ID animation there!
(i dont think this animation will looks so smooth or something.)

This animation was made by @zakki1234_lah (Frenklyn)
(you can credit to me if you want! but i think you'll not.)

]]

-- you can delete the script manually or...
script.Parent:Destroy()  -- but this method only work if you playtest the game.